// This file was procedurally generated by the Weaver Asset Linker (Window/Weaver/Asset Linker). Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro using Window/Weaver/Purchase Weaver Pro.

namespace Weaver
{
    public static class Assets
    {
    }

    public static class WeaverAssets
    {
    }
}