// This file was procedurally generated by the Weaver Layer Linker (Window/Weaver/Layer Linker). Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro using Window/Weaver/Purchase Weaver Pro.

namespace Weaver
{
    public static class Layers
    {
        #region Layers -> Edit/Project Settings/Tags and Layers

        /// <summary>Default.</summary>
        public const int Default = 0;// Mask Value: 1.

        /// <summary>TransparentFX.</summary>
        public const int TransparentFX = 1;// Mask Value: 2.

        /// <summary>Ignore Raycast.</summary>
        public const int IgnoreRaycast = 2;// Mask Value: 4.

        /// <summary>Water.</summary>
        public const int Water = 4;// Mask Value: 16.

        /// <summary>UI.</summary>
        public const int UI = 5;// Mask Value: 32.

        /// <summary>Background.</summary>
        public const int Background = 8;// Mask Value: 256.

        /// <summary>Foreground.</summary>
        public const int Foreground = 9;// Mask Value: 512.

        #endregion
    }
}